name: "pace main tests"
on:
  workflow_call:
  # pull_request:

jobs:
  pace_main_tests:
    uses: NOAA-GFDL/pace/.github/workflows/main_unit_tests.yaml@develop
    with:
      component_trigger: true
      component_name: pyFV3
