name: "Pace unit tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  pace_unit_tests:
    uses: mlee03/pace/.github/workflows/main_unit_tests.yaml@reusable_workflow
    with:
      fv3_trigger:  true
