name: "pySHiELD Translate tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  pyshield_translate_tests:
    uses:  NOAA-GFDL/PySHiELD/.github/workflows/translate.yaml@develop
    with:
      fv3_trigger:  true
