name: "pySHiELD Translate tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  pyshield_translate_tests:
    uses:  mlee03/PySHiELD/.github/workflows/translate.yaml@reusing_workflows
    with:
      fv3_trigger:  true
