name: "Translate test (subset)"
on:
  workflow_call:
    inputs:
      ndsl_hash:
        type: string
        default: TEST
        required: false
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]


# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout NDSL hash to be tested
        run: |
          echo "test"
          echo "${{inputs.ndsl_hash}}"

